export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          display_name: string | null;
          club_name: string | null;
          preferred_language: string;
          default_age_group: string | null;
          default_pitch_background: string | null;
          pdf_branding_name: string | null;
          logo_url: string | null;
          season_start_month: number;
          season_start_day: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          display_name?: string | null;
          club_name?: string | null;
          preferred_language?: string;
          default_age_group?: string | null;
          default_pitch_background?: string | null;
          pdf_branding_name?: string | null;
          logo_url?: string | null;
          season_start_month?: number;
          season_start_day?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
        Relationships: [];
      };
      drills: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          short_description: string | null;
          organization: string | null;
          coaching_points: string | null;
          variations: string | null;
          easier_version: string | null;
          harder_version: string | null;
          age_groups: string[];
          main_focus: string;
          sub_focus: string | null;
          training_blocks: string[];
          drill_type: string;
          duration_minutes: number;
          min_players: number;
          max_players: number;
          materials: Json;
          pitch_area: string | null;
          difficulty_level: number;
          intensity_level: number;
          is_favorite: boolean;
          tags: string[];
          archived_at: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          short_description?: string | null;
          organization?: string | null;
          coaching_points?: string | null;
          variations?: string | null;
          easier_version?: string | null;
          harder_version?: string | null;
          age_groups?: string[];
          main_focus: string;
          sub_focus?: string | null;
          training_blocks?: string[];
          drill_type: string;
          duration_minutes?: number;
          min_players?: number;
          max_players?: number;
          materials?: Json;
          pitch_area?: string | null;
          difficulty_level?: number;
          intensity_level?: number;
          is_favorite?: boolean;
          tags?: string[];
          archived_at?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          short_description?: string | null;
          organization?: string | null;
          coaching_points?: string | null;
          variations?: string | null;
          easier_version?: string | null;
          harder_version?: string | null;
          age_groups?: string[];
          main_focus?: string;
          sub_focus?: string | null;
          training_blocks?: string[];
          drill_type?: string;
          duration_minutes?: number;
          min_players?: number;
          max_players?: number;
          materials?: Json;
          pitch_area?: string | null;
          difficulty_level?: number;
          intensity_level?: number;
          is_favorite?: boolean;
          tags?: string[];
          archived_at?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      drill_graphics: {
        Row: {
          id: string;
          drill_id: string;
          user_id: string;
          canvas_json: Json;
          preview_image_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["drill_graphics"]["Row"]> & {
          drill_id: string;
          user_id: string;
          canvas_json: Json;
        };
        Update: Partial<Database["public"]["Tables"]["drill_graphics"]["Row"]>;
        Relationships: [];
      };
      drill_graphic_templates: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          template_json: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          template_json: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["drill_graphic_templates"]["Row"]>;
        Relationships: [];
      };
      materials: {
        Row: {
          id: string;
          user_id: string;
          drill_id: string | null;
          material_type: string;
          color: string | null;
          label: string | null;
          quantity: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["materials"]["Row"]> & {
          user_id: string;
          material_type: string;
        };
        Update: Partial<Database["public"]["Tables"]["materials"]["Row"]>;
        Relationships: [];
      };
      training_sessions: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          session_date: string | null;
          start_time: string | null;
          team_age_group: string | null;
          main_focus: string | null;
          secondary_focus: string | null;
          expected_players: number | null;
          duration_target_minutes: number | null;
          location: string | null;
          notes: string | null;
          player_groups: Json | null;
          archived_at: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["training_sessions"]["Row"]> & {
          user_id: string;
          title: string;
        };
        Update: Partial<Database["public"]["Tables"]["training_sessions"]["Row"]>;
        Relationships: [];
      };
      training_session_drills: {
        Row: {
          id: string;
          user_id: string;
          session_id: string;
          drill_id: string;
          block: string;
          order_index: number;
          planned_duration_minutes: number;
          coach_notes: string | null;
          timing_mode: "sequential" | "simultaneous";
          simultaneous_group: string | null;
          participating_groups: string[] | null;
          starting_group: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["training_session_drills"]["Row"]> & {
          user_id: string;
          session_id: string;
          drill_id: string;
        };
        Update: Partial<Database["public"]["Tables"]["training_session_drills"]["Row"]>;
        Relationships: [];
      };
      squad_players: {
        Row: {
          id: string;
          user_id: string;
          player_type: "roster" | "trial";
          first_name: string;
          last_name: string | null;
          date_of_birth: string | null;
          position: string | null;
          secondary_positions: string[] | null;
          strong_foot: string | null;
          club: string | null;
          player_email: string | null;
          parent_phone: string | null;
          player_phone: string | null;
          parent_email: string | null;
          height_cm: number | null;
          weight_kg: number | null;
          jersey_number: string | null;
          captain_status: "none" | "captain" | "vice_captain" | null;
          joined_date: string | null;
          allergies: string | null;
          medication: string | null;
          medical_notes: string | null;
          hobbies: string | null;
          development_goal: string | null;
          work_on: string | null;
          notes: string | null;
          converted_at: string | null;
          archived_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          player_type?: "roster" | "trial";
          first_name: string;
          last_name?: string | null;
          date_of_birth?: string | null;
          position?: string | null;
          secondary_positions?: string[] | null;
          strong_foot?: string | null;
          club?: string | null;
          player_email?: string | null;
          parent_phone?: string | null;
          player_phone?: string | null;
          parent_email?: string | null;
          height_cm?: number | null;
          weight_kg?: number | null;
          jersey_number?: string | null;
          captain_status?: "none" | "captain" | "vice_captain" | null;
          joined_date?: string | null;
          allergies?: string | null;
          medication?: string | null;
          medical_notes?: string | null;
          hobbies?: string | null;
          development_goal?: string | null;
          work_on?: string | null;
          notes?: string | null;
          converted_at?: string | null;
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["squad_players"]["Insert"]>;
        Relationships: [];
      };
      squad_training_events: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          start_time: string;
          end_time: string | null;
          label: string | null;
          location: string | null;
          focus: string | null;
          season_label: string | null;
          linked_training_session_id: string | null;
          status: "draft" | "prepared" | "in_progress" | "rating_open" | "completed";
          general_notes: string | null;
          created_at: string;
          updated_at: string;
          completed_at: string | null;
          archived_at: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          date: string;
          start_time: string;
          end_time?: string | null;
          label?: string | null;
          location?: string | null;
          focus?: string | null;
          season_label?: string | null;
          linked_training_session_id?: string | null;
          status?: "draft" | "prepared" | "in_progress" | "rating_open" | "completed";
          general_notes?: string | null;
          created_at?: string;
          updated_at?: string;
          completed_at?: string | null;
          archived_at?: string | null;
          deleted_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["squad_training_events"]["Insert"]>;
        Relationships: [];
      };
      squad_attendance_records: {
        Row: {
          id: string;
          user_id: string;
          event_id: string;
          player_id: string;
          planned_status: "expected" | "unavailable" | "unclear" | null;
          planned_reason: "V" | "K" | "E" | "P" | "S" | "Z" | "U" | null;
          planned_reason_note: string | null;
          planned_status_source: "default" | "manual" | "medical" | null;
          final_status: "present" | "absent" | "Z" | "V" | "K" | "E" | "P" | "S" | "U" | null;
          late_minutes: number | null;
          late_penalty_applied: boolean;
          overall_rating: number | null;
          rating_technique: number | null;
          rating_game_understanding: number | null;
          rating_intensity: number | null;
          rating_behavior: number | null;
          rating_auto_suggestion: number | null;
          coach_note: string | null;
          sensitive_note: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          event_id: string;
          player_id: string;
          planned_status?: "expected" | "unavailable" | "unclear" | null;
          planned_reason?: "V" | "K" | "E" | "P" | "S" | "Z" | "U" | null;
          planned_reason_note?: string | null;
          planned_status_source?: "default" | "manual" | "medical" | null;
          final_status?: "present" | "absent" | "Z" | "V" | "K" | "E" | "P" | "S" | "U" | null;
          late_minutes?: number | null;
          late_penalty_applied?: boolean;
          overall_rating?: number | null;
          rating_technique?: number | null;
          rating_game_understanding?: number | null;
          rating_intensity?: number | null;
          rating_behavior?: number | null;
          rating_auto_suggestion?: number | null;
          coach_note?: string | null;
          sensitive_note?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["squad_attendance_records"]["Insert"]>;
        Relationships: [];
      };
      player_coach_assessments: {
        Row: {
          id: string;
          user_id: string;
          player_id: string;
          assessment: "decision_open" | "continue_observing" | "positive_development" | "prospect_player" | "squad_candidate" | "below_required_level";
          reason: string | null;
          assessment_date: string;
          review_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          player_id: string;
          assessment: "decision_open" | "continue_observing" | "positive_development" | "prospect_player" | "squad_candidate" | "below_required_level";
          reason?: string | null;
          assessment_date?: string;
          review_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["player_coach_assessments"]["Insert"]>;
        Relationships: [];
      };
      player_development_goals: {
        Row: {
          id: string;
          user_id: string;
          player_id: string;
          title: string;
          description: string | null;
          category: "technique" | "tactical_understanding" | "decision_making" | "physical" | "mental" | "communication" | "leadership" | "goalkeeping" | "behaviour" | "individual";
          priority: "low" | "medium" | "high";
          status: "active" | "completed" | "paused" | "cancelled";
          progress: "not_started" | "in_progress" | "almost_there" | "completed";
          start_date: string;
          target_date: string | null;
          review_date: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          player_id: string;
          title: string;
          description?: string | null;
          category?: "technique" | "tactical_understanding" | "decision_making" | "physical" | "mental" | "communication" | "leadership" | "goalkeeping" | "behaviour" | "individual";
          priority?: "low" | "medium" | "high";
          status?: "active" | "completed" | "paused" | "cancelled";
          progress?: "not_started" | "in_progress" | "almost_there" | "completed";
          start_date?: string;
          target_date?: string | null;
          review_date?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["player_development_goals"]["Insert"]>;
        Relationships: [];
      };
      player_goal_actions: {
        Row: {
          id: string;
          user_id: string;
          goal_id: string;
          description: string;
          completed: boolean;
          due_date: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          goal_id: string;
          description: string;
          completed?: boolean;
          due_date?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["player_goal_actions"]["Insert"]>;
        Relationships: [];
      };
      player_observations: {
        Row: {
          id: string;
          user_id: string;
          player_id: string;
          goal_id: string | null;
          event_id: string | null;
          observation_date: string;
          category: "technique" | "tactical_understanding" | "decision_making" | "physical" | "mental" | "communication" | "leadership" | "goalkeeping" | "behaviour" | "individual" | null;
          note: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          player_id: string;
          goal_id?: string | null;
          event_id?: string | null;
          observation_date?: string;
          category?: "technique" | "tactical_understanding" | "decision_making" | "physical" | "mental" | "communication" | "leadership" | "goalkeeping" | "behaviour" | "individual" | null;
          note: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["player_observations"]["Insert"]>;
        Relationships: [];
      };
      player_contacts: {
        Row: {
          id: string;
          user_id: string;
          player_id: string;
          name: string | null;
          relationship: "mother" | "father" | "parent" | "guardian" | "emergency" | "other";
          phone: string | null;
          email: string | null;
          is_primary: boolean;
          is_emergency: boolean;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          player_id: string;
          name?: string | null;
          relationship?: "mother" | "father" | "parent" | "guardian" | "emergency" | "other";
          phone?: string | null;
          email?: string | null;
          is_primary?: boolean;
          is_emergency?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["player_contacts"]["Insert"]>;
        Relationships: [];
      };
      player_medical_periods: {
        Row: {
          id: string;
          user_id: string;
          player_id: string;
          type: "injured" | "sick";
          start_date: string;
          end_date: string | null;
          expected_return_date: string | null;
          actual_return_date: string | null;
          description: string;
          notes: string | null;
          status: "active" | "completed" | "cancelled";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          player_id: string;
          type: "injured" | "sick";
          start_date: string;
          end_date?: string | null;
          expected_return_date?: string | null;
          actual_return_date?: string | null;
          description: string;
          notes?: string | null;
          status?: "active" | "completed" | "cancelled";
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["player_medical_periods"]["Insert"]>;
        Relationships: [];
      };
      player_header_preferences: {
        Row: {
          user_id: string;
          show_height: boolean;
          show_weight: boolean;
          show_jersey_number: boolean;
          show_captain: boolean;
          show_joined_date: boolean;
          show_last_training: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          show_height?: boolean;
          show_weight?: boolean;
          show_jersey_number?: boolean;
          show_captain?: boolean;
          show_joined_date?: boolean;
          show_last_training?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["player_header_preferences"]["Insert"]>;
        Relationships: [];
      };
      coach_workspace_views: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          description: string | null;
          kind: "system" | "saved";
          system_view_id: string | null;
          configuration: Json;
          display_order: number;
          is_default: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          description?: string | null;
          kind?: "system" | "saved";
          system_view_id?: string | null;
          configuration?: Json;
          display_order?: number;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["coach_workspace_views"]["Insert"]>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
