import type { Locale } from "@/lib/i18n";
import type { ScoutingObservationRow, ScoutingPlayerRow, ScoutingTargetRow } from "@/types/database";

const en = {
  scouting: "Scouting", overview: "Overview", players: "Players", targets: "Targets",
  addPlayer: "Add player", createTarget: "Create scouting target", editPlayer: "Edit player", editTarget: "Edit target",
  back: "Back to Scouting", activeProspects: "Active prospects", shortlisted: "Shortlisted players",
  observedRecently: "Observed in the last 30 days", openTargets: "Open targets", followUpsDue: "Follow-ups due",
  dueSoon: "Targets due soon", noPlayers: "No prospects yet. Add an external player to start scouting.",
  noTargets: "No search profiles yet. Create a target for the player profile you need.",
  noObservations: "No observations yet. Add one after watching this player.",
  player: "Player", age: "Age", position: "Position", secondaryPositions: "Secondary positions",
  foot: "Preferred foot", club: "Current club", team: "Current team / age group",
  status: "Status", priority: "Priority", lastObserved: "Last observed", target: "Target",
  nextAction: "Next action", nextActionDate: "Next action date", search: "Search name or club",
  allStatuses: "All statuses", allPositions: "All positions", allFeet: "All feet",
  allPriorities: "All priorities", allTargets: "All targets", allAges: "All ages",
  sort: "Sort by", name: "Name", latest: "Last observed", open: "Open",
  firstName: "First name", lastName: "Last name", birthDate: "Birthdate",
  source: "Source", notes: "Notes", height: "Height (cm)", weight: "Weight (kg)",
  save: "Save", cancel: "Cancel", required: "This field is required.",
  possibleDuplicate: "Possible existing player", duplicateHint: "Review these records before creating a separate prospect.",
  createAnyway: "Create a separate prospect anyway", none: "None", unknown: "Not recorded",
  identified: "Identified", monitoring: "Monitoring", shortlist: "Shortlist", trial: "Trial",
  added_to_squad: "Added to squad", archived: "Archived",
  high: "High", medium: "Medium", low: "Low",
  observe_again: "Observe again", contact_club: "Contact club", invite_to_trial: "Invite to trial",
  discuss: "Discuss internally", no_action: "No action", archive: "Archive",
  match: "Match", training: "Training", tournament: "Tournament", other: "Other",
  left: "Left", right: "Right", both: "Both",
  profileOverview: "Profile", observations: "Observations", history: "History",
  addObservation: "Add observation", editObservation: "Edit observation",
  observedOn: "Date", context: "Context", event: "Event / match", observedPosition: "Observed position",
  minutes: "Minutes observed", observer: "Observer", strengths: "Strengths",
  development: "Development considerations", summary: "Summary",
  technical: "Technical", tactical: "Tactical", physical: "Physical", mental: "Mental / behaviour",
  linkedTargets: "Linked targets", linkTarget: "Link target", unlink: "Unlink",
  title: "Title", targetTeam: "Target team", positions: "Positions (comma-separated)",
  fromYear: "Birth year from", toYear: "Birth year to", desiredProfile: "Desired profile",
  targetNumber: "Players sought", deadline: "Deadline", active: "Active",
  paused: "Paused", completed: "Completed", targetProspects: "Linked prospects",
  noLinkedPlayers: "No players linked yet.", addToTarget: "Add player to target",
  inviteTrial: "Invite to trial", trialStart: "Trial starts", trialDuration: "Trial duration",
  trainingCount: "Number of trainings", endDate: "End date", trialTrainings: "Trainings",
  trialUntil: "Until date", squadProfile: "Open squad profile", scoutingHistory: "Scouting history",
  noHistory: "No history yet.", saveFailed: "Could not save. Your input is still here.",
  targetSummary: "Scouting targets describe a need, not team membership.",
  overviewHint: "Keep track of external players, observations and follow-ups.",
  days: "years", missingTeam: "Choose a team for this trial.",
  invalidDate: "Check the date or duration.", observationSaved: "Observation saved.",
  linkedPlayer: "Linked squad player", sortName: "Name", sortAge: "Age", sortRecent: "Last observed",
  sortPriority: "Priority", allClubs: "Any club", statusHistory: "Status changed",
  archivedPlayers: "Archived prospects", trialAlreadyLinked: "This prospect is already linked to a squad player.",
  created: "Player created", observation_added: "Observation added", status_changed: "Status changed",
  target_linked: "Target linked", target_removed: "Target removed", invited_to_trial: "Invited to trial",
  loadError: "Scouting could not be loaded", migrationHint: "Check the connection and confirm that the Scouting database migration has been applied.", tryAgain: "Try again"
} as const;

const de: Record<keyof typeof en, string> = {
  scouting: "Scouting", overview: "Übersicht", players: "Spieler", targets: "Suchprofile",
  addPlayer: "Spieler hinzufügen", createTarget: "Suchprofil erstellen", editPlayer: "Spieler bearbeiten", editTarget: "Suchprofil bearbeiten",
  back: "Zurück zu Scouting", activeProspects: "Aktive Talente", shortlisted: "Spieler auf der Shortlist",
  observedRecently: "In den letzten 30 Tagen gesichtet", openTargets: "Offene Suchprofile", followUpsDue: "Fällige nächste Schritte",
  dueSoon: "Bald fällige Suchprofile", noPlayers: "Noch keine Talente erfasst. Füge einen externen Spieler hinzu.",
  noTargets: "Noch keine Suchprofile. Erstelle ein Profil für den gesuchten Spielertyp.",
  noObservations: "Noch keine Beobachtungen. Erfasse eine nach der nächsten Sichtung.",
  player: "Spieler", age: "Alter", position: "Position", secondaryPositions: "Weitere Positionen",
  foot: "Starker Fuß", club: "Aktueller Verein", team: "Aktuelle Mannschaft / Altersklasse",
  status: "Status", priority: "Priorität", lastObserved: "Zuletzt gesichtet", target: "Suchprofil",
  nextAction: "Nächster Schritt", nextActionDate: "Datum des nächsten Schritts", search: "Name oder Verein suchen",
  allStatuses: "Alle Status", allPositions: "Alle Positionen", allFeet: "Alle Füße",
  allPriorities: "Alle Prioritäten", allTargets: "Alle Suchprofile", allAges: "Alle Altersgruppen",
  sort: "Sortieren nach", name: "Name", latest: "Zuletzt gesichtet", open: "Öffnen",
  firstName: "Vorname", lastName: "Nachname", birthDate: "Geburtsdatum",
  source: "Quelle", notes: "Notizen", height: "Größe (cm)", weight: "Gewicht (kg)",
  save: "Speichern", cancel: "Abbrechen", required: "Dieses Feld ist erforderlich.",
  possibleDuplicate: "Möglicherweise vorhandener Spieler", duplicateHint: "Prüfe diese Einträge, bevor du einen weiteren Spieler anlegst.",
  createAnyway: "Trotzdem als eigenen Spieler anlegen", none: "Keine", unknown: "Nicht erfasst",
  identified: "Identifiziert", monitoring: "Beobachtung", shortlist: "Shortlist", trial: "Probetraining",
  added_to_squad: "In Kader übernommen", archived: "Archiviert",
  high: "Hoch", medium: "Mittel", low: "Niedrig",
  observe_again: "Erneut sichten", contact_club: "Verein kontaktieren", invite_to_trial: "Zum Probetraining einladen",
  discuss: "Intern besprechen", no_action: "Kein Schritt", archive: "Archivieren",
  match: "Spiel", training: "Training", tournament: "Turnier", other: "Sonstiges",
  left: "Links", right: "Rechts", both: "Beidfüßig",
  profileOverview: "Profil", observations: "Beobachtungen", history: "Verlauf",
  addObservation: "Beobachtung hinzufügen", editObservation: "Beobachtung bearbeiten",
  observedOn: "Datum", context: "Kontext", event: "Ereignis / Spiel", observedPosition: "Beobachtete Position",
  minutes: "Beobachtete Minuten", observer: "Beobachter", strengths: "Stärken",
  development: "Entwicklungspunkte", summary: "Zusammenfassung",
  technical: "Technik", tactical: "Taktik", physical: "Physis", mental: "Mentalität / Verhalten",
  linkedTargets: "Verknüpfte Suchprofile", linkTarget: "Suchprofil verknüpfen", unlink: "Verknüpfung lösen",
  title: "Titel", targetTeam: "Zielmannschaft", positions: "Positionen (kommagetrennt)",
  fromYear: "Jahrgang von", toYear: "Jahrgang bis", desiredProfile: "Gesuchtes Profil",
  targetNumber: "Gesuchte Spieler", deadline: "Frist", active: "Aktiv",
  paused: "Pausiert", completed: "Abgeschlossen", targetProspects: "Verknüpfte Talente",
  noLinkedPlayers: "Noch keine Spieler verknüpft.", addToTarget: "Spieler zu Suchprofil hinzufügen",
  inviteTrial: "Zum Probetraining einladen", trialStart: "Beginn des Probetrainings", trialDuration: "Dauer des Probetrainings",
  trainingCount: "Anzahl Trainings", endDate: "Enddatum", trialTrainings: "Trainings",
  trialUntil: "Bis Datum", squadProfile: "Kaderprofil öffnen", scoutingHistory: "Scouting-Verlauf",
  noHistory: "Noch kein Verlauf.", saveFailed: "Speichern fehlgeschlagen. Deine Eingaben sind noch da.",
  targetSummary: "Suchprofile beschreiben einen Bedarf, keine Mannschaftszugehörigkeit.",
  overviewHint: "Behalte externe Spieler, Beobachtungen und nächste Schritte im Blick.",
  days: "Jahre", missingTeam: "Wähle eine Mannschaft für das Probetraining.",
  invalidDate: "Prüfe Datum oder Dauer.", observationSaved: "Beobachtung gespeichert.",
  linkedPlayer: "Verknüpfter Kaderspieler", sortName: "Name", sortAge: "Alter", sortRecent: "Zuletzt gesichtet",
  sortPriority: "Priorität", allClubs: "Alle Vereine", statusHistory: "Status geändert",
  archivedPlayers: "Archivierte Talente", trialAlreadyLinked: "Dieses Talent ist bereits mit einem Kaderspieler verknüpft.",
  created: "Spieler erstellt", observation_added: "Beobachtung hinzugefügt", status_changed: "Status geändert",
  target_linked: "Suchprofil verknüpft", target_removed: "Suchprofil entfernt", invited_to_trial: "Zum Probetraining eingeladen",
  loadError: "Scouting konnte nicht geladen werden", migrationHint: "Prüfe die Verbindung und ob die Scouting-Datenbankmigration angewendet wurde.", tryAgain: "Erneut versuchen"
};

export function scoutingCopy(locale: Locale) { return locale === "de" ? de : en; }
export const scoutingStatuses: ScoutingPlayerRow["status"][] = ["identified", "monitoring", "shortlist", "trial", "added_to_squad", "archived"];
export const scoutingPriorities: ScoutingPlayerRow["priority"][] = ["high", "medium", "low"];
export const scoutingActions: Exclude<ScoutingPlayerRow["next_action"], null>[] = ["observe_again", "contact_club", "invite_to_trial", "discuss", "none", "archive"];
export const scoutingContexts: ScoutingObservationRow["context"][] = ["match", "training", "tournament", "trial", "other"];
export const scoutingTargetStatuses: ScoutingTargetRow["status"][] = ["active", "paused", "completed", "archived"];
